AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  UploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: upload/lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: /Users/divinefavourodion/Documents/chequebase-AI/ai-expense-reporter/src/upload
